# Generated by Django 3.1.5 on 2021-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('words', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='grouping_key',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='thema',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
