# Generated by Django 3.1.5 on 2021-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='link',
            field=models.URLField(max_length=512),
        ),
        migrations.AlterField(
            model_name='image',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
