GROUPING_GROUPS_SEPARATOR = '/'

GROUPING_KEYS_KEYS_SEPARATOR = '/'
GROUPING_KEYS_KEY_SIZE = 2
GROUPING_KEYS_KEY_BASE_NUMBER = 10 ** GROUPING_KEYS_KEY_SIZE

SELECTED_TARGET_LANGUAGES_COUNT_MAX = 4

LANGUAGE_TO_SORT_NUMBER_SEPARATOR = '/'

TARGET_LANGUAGES_SELECTION_COLUMNS_COUNT = 6
