# Generated by Django 3.1.5 on 2021-11-01 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Iso_639_LanguageCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iso_639_2_code', models.CharField(max_length=3)),
                ('iso_639_1_code', models.CharField(blank=True, max_length=2)),
                ('english_name', models.CharField(max_length=64)),
                ('french_name', models.CharField(max_length=64)),
                ('german_name', models.CharField(max_length=64)),
                ('sort_number', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransliterationSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('sort_number', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
