# Generated by Django 3.1.5 on 2021-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_pronunciationform'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranscriptionSystem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sort_number', models.FloatField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='TransliterationScript',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('sort_number', models.FloatField(blank=True, default=0)),
            ],
        ),
    ]
