# Generated by Django 3.1.5 on 2021-11-05 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0004_auto_20211105_1656'),
        ('languages', '0003_transcriptionsystem_transliterationscript'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TransliterationSystem',
        ),
        migrations.AlterField(
            model_name='iso_639_languagecode',
            name='english_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='iso_639_languagecode',
            name='french_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='iso_639_languagecode',
            name='german_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='pronunciationform',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
