import os


SORT_NUMBER_DEFAULT = 0
SORT_NUMBER_INC_DEFAULT = 1

DATA_FILES_DIR_NAME = 'data_files'
DATA_FILES_DIR = os.path.join('../', DATA_FILES_DIR_NAME)

DATA_FILE_NAME_THEMES = 'themes.csv'
THEME_NAME_COLUMN = 0
THEME_NAME_HEADER = 'Name'

DATA_FILE_NAME_ENDING_BASE_WORDS = '-base-words.csv'
BASE_WORD_TEXT_COLUMN = 0
BASE_WORD_TEXT_HEADER = 'Text'

BASE_WORDS_LIMIT_MAX_BY_THEME = 1000

BASE_WORD_COLUMN = 0
BASE_WORD_HEADER = 'Base Word'
GROUPING_COLUMN = 1
GROUPING_HEADER = 'Grouping'
GROUPING_KEY_COLUMN = 2 
GROUPING_KEY_HEADER = 'Grouping Key'

DATA_FILE_NAME_ENDING_WORDS_IMAGES = '-words-images.csv'
IMAGE_COLUMN = 2 
IMAGE_HEADER = 'Image'
