# Generated by Django 3.1.5 on 2021-11-04 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sound',
            name='name',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
