# Generated by Django 3.1.5 on 2021-11-01 23:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('languages', '0001_initial'),
        ('sounds', '0001_initial'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meaning',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('definition', models.TextField(blank=True)),
                ('sort_number', models.FloatField(blank=True, default=0)),
                ('images', models.ManyToManyField(blank=True, related_name='images_Meaning_related', to='images.Image')),
            ],
        ),
        migrations.CreateModel(
            name='SpellingLanguage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.FloatField(blank=True, default=0)),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_SpellingLanguage_related', to='languages.iso_639_languagecode')),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_SpellingLanguage_related', to='languages.transliterationsystem')),
            ],
        ),
        migrations.CreateModel(
            name='Spelling',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('sort_number', models.FloatField(blank=True, default=0)),
                ('spelling_language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='spelling_language_Spelling_related', to='phrases.spellinglanguage')),
            ],
        ),
        migrations.CreateModel(
            name='Pronunciation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sort_number', models.FloatField(blank=True, default=0)),
                ('sound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sound_Pronunciation_related', to='sounds.sound')),
                ('spellings', models.ManyToManyField(blank=True, related_name='spellings_Pronunciation_related', to='phrases.Spelling')),
            ],
        ),
        migrations.CreateModel(
            name='Phrase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('synonym_sort_number', models.FloatField(blank=True, default=0)),
                ('sort_number', models.FloatField(blank=True, default=0)),
                ('examples', models.ManyToManyField(blank=True, related_name='_phrase_examples_+', to='phrases.Phrase')),
                ('language', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='language_Phrase_related', to='languages.iso_639_languagecode')),
                ('meaning', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meaning_Phrase_related', to='phrases.meaning')),
                ('pronunciation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pronunciation_Phrase_related', to='phrases.pronunciation')),
                ('spellings', models.ManyToManyField(blank=True, related_name='spellings_Phrase_related', to='phrases.Spelling')),
            ],
        ),
    ]
