# Generated by Django 3.1.5 on 2021-11-04 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phrases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phrase',
            name='pronunciation_sort_number',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
