# Generated by Django 3.1.5 on 2021-11-05 00:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0002_pronunciationform'),
        ('phrases', '0002_phrase_pronunciation_sort_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='pronunciation',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='form_Pronunciation_related', to='languages.pronunciationform'),
        ),
    ]
