# Generated by Django 3.1.5 on 2021-11-05 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('languages', '0003_transcriptionsystem_transliterationscript'),
        ('phrases', '0003_pronunciation_form'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transcription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True)),
                ('sort_number', models.FloatField(blank=True, default=0)),
                ('system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='system_Transcription_related', to='languages.transcriptionsystem')),
            ],
        ),
        migrations.RemoveField(
            model_name='pronunciation',
            name='spellings',
        ),
        migrations.RemoveField(
            model_name='spelling',
            name='spelling_language',
        ),
        migrations.AddField(
            model_name='phrase',
            name='example_sort_number',
            field=models.FloatField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='spelling',
            name='script',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='script_Spelling_related', to='languages.transliterationscript'),
        ),
        migrations.DeleteModel(
            name='SpellingLanguage',
        ),
        migrations.AddField(
            model_name='pronunciation',
            name='transcriptions',
            field=models.ManyToManyField(blank=True, related_name='transcriptions_Pronunciation_related', to='phrases.Transcription'),
        ),
    ]
